scripts: gen_relocate_app: skip preprocessor defines
fancom/zephyr pull request #52
Opened 2022-01-28 10:17 UTC by JvanDooren

Skipping preprocessor defines as input line

Signed-off-by: Jeroen van Dooren <jeroen.van.dooren@nobleo.nl>

2022-01-28 12:28 UTC, heinwessels requested changes

2022-01-28 12:28 UTC, heinwessels commented on scripts/gen_relocate_app.py
> +        if ':' in line:
A cleaner way would be:

```python
for line in args.input_rel_dict.split(';'):
        
        if not ':' in line:
            # ignore custom lines with only preprocessor defines, separated by a ';'
            continue

        mem_region, file_name = line.split(':', 1)
        ....
```

2022-02-01 07:55 UTC, JvanDooren commented on scripts/gen_relocate_app.py
> +        if ':' in line:
Indeed, changed

2022-02-01 08:12 UTC, heinwessels approved these changes

2022-02-01 08:22 UTC, merged